### ISSUE TITLE
报告日期是约 3 个月前的，如何更新呢？

### ISSUE THREAD

**Issue by TommyLemon** [oss-compass/compass-projects-information#150]
APIJSON Tencent on Gitee updated on 2022-11-28 这个日期不对
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/5738175/220566662-8ddd5941-bffb-464b-84cf-0526cbda8495.png">

应该是 2023-2-21：
https://gitee.com/Tencent/APIJSON
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/5738175/220567244-dcf4f53e-9c2e-4641-8bb4-5dc692a3f09c.png">

可能分析报告的日期是去年的，请问怎么更新这个报告呢？

**Comment by eyehwan** [comment]
我们会周期性迭代更新数据；当前因为前期准备产品发布，暂停了数据更新，我们会马上恢复。

**Comment by TommyLemon** [comment]
这样啊，赞

**Comment by EdmondFrank** [comment]
已更新 https://compass.gitee.com/analyze?label=https%3A%2F%2Fgitee.com%2FTencent%2FAPIJSON&level=repo

**Comment by TommyLemon** [comment]
赞，现在 APIJSON 的 Gitee 和 GitHub 数据接近了哈哈
https://compass.gitee.com/analyze?label=https%3A%2F%2Fgitee.com%2FTencent%2FAPIJSON&level=repo&range=Since%202000&label=https%3A%2F%2Fgithub.com%2FTencent%2FAPIJSON
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/5738175/220834190-b29ca859-7dee-44e2-83f4-8a163476d154.png">
