### ISSUE TITLE
Can anyone delete a pr automatically created by oss-compass bot?

### ISSUE THREAD

**Issue by YichuanSun** [oss-compass/compass-projects-information#325]
I commit an request while the bot creates a pr then @ my github account, could the administrator delete the pr? I don't want to reveal my github account. Thanks!

**Comment by eyehwan** [comment]
I can remove your account mentioned by this pr.

**Comment by YichuanSun** [comment]
@eyehwan can you delete this issue too? Thanks.

**Comment by eyehwan** [comment]
No one can delete this issue, except for Github per se. Only reason they would help delete some issue or pr is that it contains some sensitive data.
