### ISSUE TITLE
Back End: add field of community url to yml file(在community level yml文件增加 社区链接字段)

### ISSUE THREAD

**Issue by eyehwan** [oss-compass/compass-projects-information#413]
Need to add link of community, like:
1. community official url
2. github/gitee org url.

![Image](https://user-images.githubusercontent.com/1535756/236383277-bad5272f-b94f-4b8f-8c2e-676e2bc468ab.png)

**Comment by EdmondFrank** [comment]
Updated to gray environment, front-end developers can be tested
