### ISSUE TITLE
link on website broken for 'contact us'

### ISSUE THREAD

**Issue by shsingh** [oss-compass/compass-projects-information#592]
The following link: https://oss-compass.org/analyze/docs/community is referenced for the 'contact us' section.

for example at the following link: https://oss-compass.org/analyze/sl88kmfu#organizations_activity_org_count

**Comment by eyehwan** [comment]
@shsingh Thanks for your bug report.
@coder-sett , we need to fix this wrong link .

**Comment by coder-sett** [comment]
@shsingh wrong link fixed，Thanks again

**Comment by shsingh** [comment]
tried checking and it seems letsencrypt cert has expired on site

**Comment by eyehwan** [comment]
Yes, already fixed yesterday.
