### ISSUE TITLE
AHP consistency ratio for model in webpage is incorrect.

### ISSUE THREAD

**Issue by kid9** [oss-compass/compass-projects-information#664]
in the [webpage](https://oss-compass.org/docs/metrics-models/productivity/community-service-and-support/) for community-service-and-support model, the shown consistency_ratio was 1.36, which is not correct. IT SHOULD be a near 0 value.

![image](https://github.com/oss-compass/compass-projects-information/assets/5262281/555586e6-ad79-40bc-96a3-07cc3b468963)

**Comment by eyehwan** [comment]
@kid9 Sorry for late response, we will check on it. Thanks a lot!

**Comment by eyehwan** [comment]
Hi we just check original compute result, yes, you are right, we fill the wrong number. @lishengbao you can help update the value. 

original result:
![image](https://github.com/oss-compass/compass-projects-information/assets/1535756/d257bee0-19fc-462f-8cff-cbd000b2ea4b)

**Comment by lishengbao** [comment]
https://github.com/oss-compass/docs-zh/pull/3
