### ISSUE TITLE
【BUG】收集的信息有问题

### ISSUE THREAD

**Issue by Fgaoxing** [oss-compass/compass-projects-information#943]
![image](https://github.com/oss-compass/compass-projects-information/assets/92655031/ad71df4c-ee32-4c3d-9f40-dc19a6635478)
该仓库并没有这个人

**Comment by Fgaoxing** [comment]
这个也只有我一个人
![image](https://github.com/oss-compass/compass-projects-information/assets/92655031/e0e498c2-2eae-4312-b23b-68009014efc5)
![image](https://github.com/oss-compass/compass-projects-information/assets/92655031/54bbbeb9-9877-4b4a-bca2-fb2c14951729)

**Comment by lishengbao-small** [comment]
项目深度洞察的贡献者包含了star， fork，issue， pr等事情的贡献者；ning0818可能是fork您项目的贡献者

**Comment by lishengbao** [comment]
项目深度洞察的贡献者不仅仅是代码贡献者, 还包含了star, fork, issue, pr等事件, ning0818是star该项目的贡献者;  你可以点击"查看洞察详情" 的领域画像有具体相关事件
![image](https://github.com/oss-compass/compass-projects-information/assets/53640896/4f66b457-1a96-4af6-bd47-42ae4151db73)

**Comment by eyehwan** [comment]
@lishengbao 这是我们的算法bug，按照规则star，fork贡献从来都不应该被计入核心、常客贡献者，这类贡献只属于访客贡献。 @Fgaoxing 的comment 很准确，目前咱们的呈现方式很奇葩。

**Comment by lishengbao** [comment]
> @lishengbao 这是我们的算法bug，按照规则star，fork贡献从来都不应该被计入核心、常客贡献者，这类贡献只属于访客贡献。 @Fgaoxing 的comment 很准确，目前咱们的呈现方式很奇葩。
> 
> ![image](https://private-user-images.githubusercontent.com/1535756/300834494-3aeb5d65-7353-4faa-bb53-d2feb06036a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTQ5ODQsIm5iZiI6MTcwNjY5NDY4NCwicGF0aCI6Ii8xNTM1NzU2LzMwMDgzNDQ5NC0zYWViNWQ2NS03MzUzLTRmYWEtYmI1My1kMmZlYjA2MDM2YTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMDk1MTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2MwYjkzNDQxNmM3N2YzNjE5ZmM5Zjk5OTY3NDFiMjM1NjEyNjI1YzljMjk4NDYwMDkxNzY4OWIwNTYxNzhkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ETGLoRzdN-ETPkGtMDCXfbREzuICSntxfmoWsfaIleg)

已修复!
